on: workflow_dispatch
#name和env的环境针对的是
name: 8Mi_Yile
env:  
  org_user: 8MiYile
  
jobs:
  auto-sync-repo-single:
    name: Auto Sync Task List
    uses: ./.github/workflows/main.yml
    with:
      task-list: ./list/8Mi_Yile.list
