on: 
  workflow_dispatch:
  schedule:
   - cron: '0 10 * * *'
#name和env的环境针对的是
name: 8Mi_Yile
  
jobs:
  auto-sync-repo-single:
    name: List
    secrets: inherit
    uses: ./.github/workflows/main.yml
    with:
      task-list-file: .github/list/8Mi_Yile.list
