name: 8Mi Auto Sync (Multi Repo)
# It works fine, the next build is solved by the machine automatically
on: 
  workflow_dispatch:
    inputs:
      task-list-file:
        required: true
        type: string
  workflow_call:
    inputs:
      task-list-file:
        required: true
        type: string
      org-user:
        required: false
        type: string
  # 需要调试的时候，再打开这个功能
  #workflow_dispatch:
  # 定时器 默认
  #schedule:
    #- cron: '* 0/1 * * *'
  
env:
  TZ: Asia/Shanghai

jobs:
  Init:
    runs-on: ubuntu-latest
    name: Initialization 
    outputs:
      result: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - # ${{ steps.get-task-list.outputs.result }}
        id: set-matrix
        run: |
          echo "matrix="`cat ${{ inputs.task-list-file }} `"">> $GITHUB_OUTPUT
    
  Sync-Task:
    # if仅仅是防止有人放在非Auto-Sync-Repo仓库内使用
    # if: ${{ vars.VAR_8MI_TECH_FORK_SYNC_BOOLEAN == 'true' }}
    needs: Init
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.Init.outputs.result) }}
    name: ${{ matrix.repo }} (${{ matrix.branch }})
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_SYNC_GH_KEY }}
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          path: ${{ matrix.repo }}
      -
        name: Sync Repo
        run: |
          echo "::group::Set github-actions bot"
          cd ${{ matrix.repo }}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "::group::Downloading Zip source"
          cd -
          wget -O Yile.zip https://github.com/${{ matrix.from_org_user }}/${{ matrix.repo }}/archive/refs/heads/${{ matrix.branch }}.zip
          echo "::group::Unzip source"
          unzip Yile.zip
          echo "::group::Move to this repo"
          rsync -avz --exclude=".git" --delete ${{ matrix.repo }}-${{ matrix.branch }}/ ${{ matrix.repo }}/
          echo "::group::Remove Download's File"
          rm -v Yile.zip
          rm -rfdv ${{ matrix.repo }}-${{ matrix.branch }}
          echo "::group::Create Git Commit"
          cd -
          git add *
          git commit -a -m "Auto Sync From"${{ matrix.org_name }}
      -
        name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTO_SYNC_GH_KEY }}
          branch: refs/heads/${{ matrix.branch }}
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          directory: ${{ matrix.repo }}
