name: 8Mi Auto Sync (Multi Repo)
# It works fine, the next build is solved by the machine automatically
on: 
  workflow_call:
    inputs:
      task-list-file:
        required: true
        type: string
    outputs:
       task-list: # id of the output
         description: task list
         value: ${{ steps.get-task-list.outputs.result }}
  # 需要调试的时候，再打开这个功能
  #workflow_dispatch:
  # 定时器 默认
  #schedule:
    #- cron: '* 0/1 * * *'
  
env:
  TZ: Asia/Shanghai
  task-list: ${{ jobs.Initialization.steps.get-task-list.outputs.result }}

jobs:
  Initialization:
    runs-on: ubuntu-latest
    name: Initialization Task List
    steps:
      - # ${{ steps.get-task-list.outputs.result }}
        name: Get Task List
        id: get-task-list
        run: echo "result=$(echo  $(curl https://github.com/${{ github.repository }}/raw/main/${{ inputs.task-list-file }}) )" >> $GITHUB_OUTPUT
        shell: bash
  Sync-Task:
    # if仅仅是防止有人放在非Auto-Sync-Repo仓库内使用
    # if: ${{ vars.VAR_8MI_TECH_FORK_SYNC_BOOLEAN == 'true' }}
    needs: Initialization
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ env.task-list }}
    name: ${{ matrix.repo }} / ${{ matrix.branch }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_SYNC_GH_KEY }}
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          path: ${{ matrix.repo }}
      -
        name: Sync Repo
        run: |
          echo "::group::Set github-actions bot"
          cd ${{ matrix.repo }}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "::group::Downloading Zip source"
          cd -
          wget -O Yile.zip https://github.com/${{ matrix.from_org_user }}/${{ matrix.repo }}/archive/refs/heads/${{ matrix.branch }}.zip
          echo "::group::Unzip source"
          unzip Yile.zip
          echo "::group::Move to this repo"
          rsync -avz --exclude=".git" --delete ${{ matrix.repo }}-${{ matrix.branch }}/ ${{ matrix.repo }}/
          echo "::group::Remove Download's File"
          rm -v Yile.zip
          rm -rfdv ${{ matrix.repo }}-${{ matrix.branch }}
          echo "::group::Create Git Commit"
          cd -
          git add *
          git commit -a -m "Auto Sync From"${{ matrix.org_name }}
      -
        name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTO_SYNC_GH_KEY }}
          branch: refs/heads/${{ matrix.branch }}
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          directory: ${{ matrix.repo }}
